pipeline {
    agent any
    environment {
        DOCKER_IMAGE = "ashokkumaraligeri/myapp:1.0"
    }
    stages {
        stage('Clone') {
            steps {
                git 'https://github.com/ashokyan/viyu1.git'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }
        stage('Docker Build & Push') {
            steps {
                script {
                    sh "docker build -t $DOCKER_IMAGE ."
                    withCredentials([string(credentialsId: 'ThisisJune@25', variable: 'DOCKER_PASS')]) {
                        sh 'echo $DOCKER_PASS | docker login -u ashokkumaraligeri --password-stdin'
                        sh "docker push $DOCKER_IMAGE"
                    }
                }
            }
        }
        stage('Deploy to K8s') {
            steps {
                sh 'kubectl apply -f k8s/deployment.yaml'
                sh 'kubectl apply -f k8s/service.yaml'
            }
        }
    }
}

